steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy stripetojira \
          --runtime=nodejs20 \
          --trigger-http \
          --entry-point=stripetojira \
          --allow-unauthenticated \
          --region=europe-west2 \
          --set-env-vars=JIRA_JSM_SERVICE_DESK_ID=${_JIRA_JSM_SERVICE_DESK_ID},JIRA_JSM_PROJECT_KEY=${_JIRA_JSM_PROJECT_KEY},JIRA_JSM_REQUEST_TYPE_ID=${_JIRA_JSM_REQUEST_TYPE_ID}
  
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services add-iam-policy-binding stripetojira \
          --member="allUsers" \
          --role="roles/run.invoker" \
          --region=europe-west2

availableSecrets:
  secretManager:
  - versionName: projects/jira-stripe-integration/secrets/STRIPE_SECRET_KEY/versions/latest
    env: STRIPE_SECRET_KEY
  - versionName: projects/jira-stripe-integration/secrets/STRIPE_WEBHOOK_SECRET/versions/latest
    env: STRIPE_WEBHOOK_SECRET
  - versionName: projects/jira-stripe-integration/secrets/JIRA_EMAIL/versions/latest
    env: JIRA_EMAIL
  - versionName: projects/jira-stripe-integration/secrets/JIRA_API_TOKEN/versions/latest
    env: JIRA_API_TOKEN
  - versionName: projects/jira-stripe-integration/secrets/JIRA_DOMAIN/versions/latest
    env: JIRA_DOMAIN
  
substitutions:
  _JIRA_JSM_SERVICE_DESK_ID: "6"
  _JIRA_JSM_PROJECT_KEY: "YOK"
  _JIRA_JSM_REQUEST_TYPE_ID: "47"
