steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy stripetojira \
          --runtime=nodejs20 \
          --trigger-http \
          --entry-point=stripetojira \
          --allow-unauthenticated \
          --region=europe-west2 \
          --update-secrets=STRIPE_SECRET_KEY=stripe-secret-key,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret,JIRA_EMAIL=jira-email,JIRA_API_TOKEN=jira-api-token,JIRA_DOMAIN=jira-domain \
          --set-env-vars=JIRA_JSM_SERVICE_DESK_ID=${_JIRA_JSM_SERVICE_DESK_ID},JIRA_JSM_PROJECT_KEY=${_JIRA_JSM_PROJECT_KEY},JIRA_JSM_REQUEST_TYPE_ID=${_JIRA_JSM_REQUEST_TYPE_ID}
  
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services add-iam-policy-binding stripetojira \
          --member="allUsers" \
          --role="roles/run.invoker" \
          --region=europe-west2

substitutions:
  _JIRA_JSM_SERVICE_DESK_ID: "6"
  _JIRA_JSM_PROJECT_KEY: "YOK"
  _JIRA_JSM_REQUEST_TYPE_ID: "47"

options:
  logging: CLOUD_LOGGING_ONLY
  # Cosmetic change to force deployment:
  machineType: 'E2_MEDIUM'
